language: cpp

os:
  - linux
  addons:
    apt:
      sources:
        ubuntu-toolchain-r-test
      packages:
        - gcc-8
        - g++-8
        - ninja-build
  - osx
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-7
      packages:
        - clang-7.0

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - freeglut3-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libxinerama-dev
    - libjpeg-dev
    - libxi-dev
    - libxmu-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - pip install --user codecov

  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.1-Darwin-x86_64.tar.gz   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then tar -xzf cmake-3.13.1-Darwin-x86_64.tar.gz                                                    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export PATH=$PWD/cmake-3.13.1-Darwin-x86_64/CMake.app/Contents/bin:$PATH                      ;fi
###############################################################################################################################################
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.13.1-Linux-x86_64.tar.gz                                                     ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.13.1-Linux-x86_64/bin:$PATH                                          ;fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                                   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install llvm                                                                             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install ninja                                                                            ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_C_COMPILER=${CC}                                                                 ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_CXX_COMPILER=${CXX}                                                              ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_LINKER=clang++-7                                                                 ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ${CXX} --version                                                                              ;fi

  # OSX Setup
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                                   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install freeglut                                                                         ;fi

  # Link gcc-7 and g++-7 to their standard commands
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++                                                  ;fi
  # Export CC and CXX to tell cmake which compiler to use
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=/usr/bin/gcc-8                                                                      ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=/usr/bin/g++-8                                                                     ;fi
  # Check versions of gcc, g++ and cmake
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gcc -v && g++ -v && cmake --version                                                           ;fi


before_script:
  - mkdir build
  - cd build
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -G "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DOMP=ON" ..                                     ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then cmake "-DCMAKE_BUILD_TYPE=Debug" "-DOMP=ON" ..                                               ;fi

script:
  - cmake --build .

after_success:
  - codecov --file coverage/lcov.info --disable search
