site_name:          Walkers
repo_url:           https://github.com/Nico-Curti/Walkers
site_description:   Random Walkers and Nature-based Optimizer simulator
size_author:        https://www.unibo.it/sitoweb/nico.curti2

theme:              jekyll-theme-slate

extra_css:          assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
